CovOpen/CovMapper

- apps/official/index.ts
- src/app-config.types.ts
- src/components/CovMap.tsx
- src/components/Legend.tsx
- src/lib/expression.ts
This might need a redesign because it covers a good portion of the map
Fixes #24
> Add a legend

- src/components/WelcomeStepsModal/WelcomeModal1.tsx
- src/components/WelcomeStepsModal/WelcomeModalPostalCode.tsx
- src/components/WelcomeStepsModal/WelcomeStepsModal.tsx
- src/components/WelcomeStepsModal/useCommonWelcomeModalStyles.ts
Look and Feel an Figma angepasst
* Farbe der Buttons wenn im Fokus/Aktiv/Hover
* viele Abstände
* autofocus auf PLZ Eingabe und Möglichkeit mit Enter zu bestätigen
> Welcome screens 3

- .gitignore
- src/components/FeatureInfo.tsx
replacing Popup for infobox with bottom-oriented Drawer. May need some width constraints to not cover up zoom element.
> Feature/cov feature info/position

- .github/workflows/bundle-size.yml
This tries to fix the checkout action syntax in the bundle size workflow.
> Move checkout action args under 'with' key

- apps/official/components/pages/Privacy.tsx
> Datenschutz

- src/components/WelcomeStepsModal/WelcomeModalPostalCode.tsx
> Allow postal codes that start with 0

- src/App.tsx
- src/app.css
- src/components/NavBar.tsx
Please note that this does change the scrolling behavior. Please test before reviewing.
> fix: Properly calculate NavBar height based on viewport width

- apps/official/index.ts
- apps/official/static/locales/de/translation.json
- apps/official/static/locales/en/translation.json
- src/app-config.types.ts
- src/components/CovMap.tsx
- src/components/NavBar.tsx
Reorders menu items and adds a divider to separate actually useful pages from legal stuff and other things.
> chore: reorder menu items

- .github/workflows/pr-title-check.yml
before it just failed on wrongly formatted PR titles and displayed the comment on well formatted PRs.
Now everything works as expected.
> chore: fix pr-title check

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/pr-check.yml
- .github/workflows/pr-preview-teardown.yml
- .github/workflows/pr-title-check.yml
- apps/official/components/pages/ContactBehavior.tsx
- apps/official/components/pages/Credits.tsx
- apps/official/components/pages/Faq.tsx
- apps/official/components/pages/Imprint.tsx
- apps/official/components/pages/Privacy.tsx
- apps/official/components/pages/SymptomLevel.tsx
- hosting/docker-compose.yml
- src/components/FixedSearch.tsx
- src/components/WelcomeStepsModal/WelcomeModal1.tsx
- src/components/WelcomeStepsModal/WelcomeModal2.tsx
- run prettier on all the files
> chore: cleanup

- .github/workflows/pr-title-check.yml
Issue https://github.com/aslafy-z/conventional-pr-title-action/issues/63 was resolved 
add version tag so it does not automatically update
> chore: fix title check

- src/components/CovMap.tsx
> fix: no zoom buttons on mobile

- apps/official/components/pages/Faq.tsx
> chore: render accordion content as component children

- apps/official/static/images/logo.svg
should be centered on the loading screen now :)
> fix: center logo

- src/state/thunks/fetchMappedSet.ts
> fix: avoid fetching data/geojson multiple times

- apps/official/components/pages/Faq.tsx
> fix: Update Faq.tsx

- src/state/thunks/fetchMappedSet.ts
Resetting the date tolast day (up to three times) if data is not available (404)
> feat: handle unavailable data for current date

- src/components/Search.tsx
- src/state/thunks/fetchMappedSet.ts
> fix(Search): fixed mobile keyboard not closing when a search suggestion is selected

- .github/workflows/auto-assign-to-project.yml
This will add new issues and pull requests to the project overview dashboard
> chore: add auto assign to project workflow

- src/index.tsx
- static/locales/de/common.json
- static/locales/en/common.json
> fix: add error screen

- .all-contributorsrc
- README.md
> chore: add contributors

- apps/official/components/pages/Credits.tsx
- apps/official/components/pages/Privacy.tsx
fixed minor dom validation and missing key errors in pages
> fix(Pages): more dom validation fixes and added missing keys
